trigger:
  branches:
    include:
      - Dev

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install Dependencies'

- script: |
    npm run build
  displayName: 'Build React App'

- task: SonarCloudPrepare@4
  inputs:
    SonarCloud: 'SonarCloud-ecommerce'
    organization: 'e-commerce-56'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'e-commerce-56_e-commerce-56'
    cliProjectName: 'e-commerce-56'
    cliSources: '.'

- task: SonarCloudAnalyze@4
  displayName: 'Run Sonar Analysis'

- task: SonarCloudPublish@4
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish Quality Gate'
